name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Image Tag
      id: tag
      run: |
        RANDOM_TAG=$(( RANDOM % 90 + 10 ))
        echo "TAG=$RANDOM_TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: siddhartha54/chatapp-frontend:${{ steps.tag.outputs.TAG }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: siddhartha54/chatapp-backend:${{ steps.tag.outputs.TAG }}

    - name: Update Kubernetes Deployment YAMLs
      run: |
        sed -i "s|image: .*/chatapp-frontend:.*|image: siddhartha54/chatapp-frontend:${{ steps.tag.outputs.TAG }}|" k8s/frontend-deployment.yaml
        sed -i "s|image: .*/chatapp-backend:.*|image: siddhartha54/chatapp-backend:${{ steps.tag.outputs.TAG }}|" k8s/backend-deployment.yaml

    - name: Commit and Push updated deployment YAMLs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/frontend-deployment.yaml k8s/backend-deployment.yaml
        if ! git diff-index --quiet HEAD; then
          git commit -m "Deploy: Update image tags to ${{ steps.tag.outputs.TAG }}"
          git push
        else
          echo "No deployment changes to commit."
        fi


